name: 'projeto_prod'
version: '1.0.0'

profile: 'projeto_prod'


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:       
  - "target"
  - "dbt_packages"


models:
  projeto_prod:
    staging:
      schema: stg
      tag: ['staging']
      +materialized: table
    
    intermediate:
      schema: int
      +materialized: ephemeral
      tag: ['intermediate']
    
    marts:
      schema: marts
      +materialized: table
      tag: ['marts']
  
  seeds:
    projeto_prod
      schema: raw
      tags: ['seed']

